In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
#51
#各ファイル読み込んでリスト化

#FORMAT: ID \t TITLE \t URL \t PUBLISHER \t CATEGORY \t STORY \t HOSTNAME \t TIMESTAMP

test_lines_list = []
valid_lines_list = []
train_lines_list = []


with open("test.txt") as f1:
    for line in f1.readlines():
        test_lines_list.append(line.strip().split('\t')[1])
with open("valid.txt") as f2:
    for line in f2.readlines():
        valid_lines_list.append(line.strip().split('\t')[1])
with open("train.txt") as f3:
    for line in f3.readlines():
        train_lines_list.append(line.strip().split('\t')[1])

print(test_lines_list[0:3])
print(valid_lines_list[0:3])
print(train_lines_list[0:3])

print(len(test_lines_list))
print(len(valid_lines_list))
print(len(train_lines_list))

doc_lines_list = []
print(type(doc_lines_list))
doc_lines_list.extend(test_lines_list)
doc_lines_list.extend(valid_lines_list)
doc_lines_list.extend(train_lines_list)

print(len(doc_lines_list))

['Call the orthodontist! Miley Cyrus snarls as she shows off her joke snaggle  ...', 'Comcast-Time Warner Merger Faces State-Level Investigation', 'Spotify hits 40m users as Apple finalises Beats deal']
['Aspirin to Prevent Heart Attack Should Be Limited, FDA Says (2)', 'PRECIOUS-Gold slips; platinum extends losses as Sth African strike ends', "Kerry Washington - Kerry Washington: Filming while pregnant is a 'challenge'"]
['Crumbs Surges After CNBC Says Lemonis Considering Rescue', 'Net Neutrality Must Be Defended', 'Gas prices fall over a penny in New Hampshire']
1336
1334
10685
<class 'list'>
13355


In [22]:

# CountVectorizer 
c_vectorizer = CountVectorizer(binary=True)

# ベクトル化 
c_vectorizer.fit(doc_lines_list)
print(type(c_vectorizer))

#特徴量の計算
X_test = c_vectorizer.transform(test_lines_list)
X_valid = c_vectorizer.transform(valid_lines_list)
X_train = c_vectorizer.transform(train_lines_list)

# print(type(X_test))
print(X_test)

#抽出した単語と出現回数の辞書
voc_count_dict = c_vectorizer.vocabulary_
# print(type(voc_count_dict))
# print(len(voc_count_dict))
# print(voc_count_dict)

#抽出単語/各行　値：出現したかのバイナリ
pd.DataFrame(X_test.toarray(), columns=c_vectorizer.get_feature_names())
# test_feature = X_test.toarray()
# print(test_feature)

<class 'sklearn.feature_extraction.text.CountVectorizer'>
  (0, 1100)	1
  (0, 2172)	1
  (0, 3371)	1
  (0, 5990)	1
  (0, 6821)	1
  (0, 8026)	1
  (0, 8681)	1
  (0, 8826)	1
  (0, 11170)	1
  (0, 11256)	1
  (0, 11521)	1
  (0, 11533)	1
  (0, 12537)	1
  (1, 2810)	1
  (1, 4704)	1
  (1, 6616)	1
  (1, 7311)	1
  (1, 7941)	1
  (1, 11871)	1
  (1, 12661)	1
  (1, 13527)	1
  (2, 225)	1
  (2, 992)	1
  (2, 1100)	1
  (2, 1492)	1
  :	:
  (1333, 3809)	1
  (1333, 4095)	1
  (1333, 5673)	1
  (1333, 8732)	1
  (1333, 11157)	1
  (1333, 13011)	1
  (1333, 13191)	1
  (1333, 13238)	1
  (1333, 13365)	1
  (1334, 3203)	1
  (1334, 8463)	1
  (1334, 8775)	1
  (1334, 12419)	1
  (1334, 13741)	1
  (1335, 4900)	1
  (1335, 4973)	1
  (1335, 5123)	1
  (1335, 6685)	1
  (1335, 6979)	1
  (1335, 7337)	1
  (1335, 9279)	1
  (1335, 12688)	1
  (1335, 13234)	1
  (1335, 13256)	1
  (1335, 13401)	1


00  07  08  09  0ff  0ut  10  100  1000  10000   ...    zone  zooey  \
0      0   0   0   0    0    0   0    0     0      0   ...       0      0   
1      0   0   0   0    0    0   0    0     0      0   ...       0      0   
2      0   0   0   0    0    0   0    0     0      0   ...       0      0   
3      0   0   0   0    0    0   0    0     0      0   ...       0      0   
4      0   0   0   0    0    0   0    0     0      0   ...       0      0   
5      0   0   0   0    0    0   0    0     0      0   ...       0      0   
6      0   0   0   0    0    0   0    0     0      0   ...       0      0   
7      0   0   0   0    0    0   0    0     0      0   ...       0      0   
8      0   0   0   0    0    0   0    0     0      0   ...       0      0   
9      0   0   0   0    0    0   0    0     0      0   ...       0      0   
10     0   0   0   0    0    0   0    0     0      0   ...       0      0   
11     0   0   0   0    0    0   0    0     0      0   ...       0      0   
12     0   0   0   0    0    0   0    0     0      0   ...       0      0   
13     0   0   0   0    0    0   0    0     0      0   ...       0      0   
14     0   0   0   0    0    0   0    0     0      0   ...       0      0   
15     0   0   0   0    0    0   0    0     0      0   ...       0      0   
16     0   0   0   0    0    0   0    0     0      0   ...       0      0   
17     0   0   0   0    0    0   0    0     0      0   ...       0      0   
18     0   0   0   0    0    0   0    0     0      0   ...       0      0   
19     0   0   0   0    0    0   0    1     0      0   ...       0      0   
20     0   0   0   0    0    0   0    0     0      0   ...       0      0   
21     0   0   0   0    0    0   0    0     0      0   ...       0      0   
22     0   0   0   0    0    0   0    0     0      0   ...       0      0   
23     0   0   0   0    0    0   0    0     0      0   ...       0      0   
24     0   0   0   0    0    0   0    0     0      0   ...       0      0   
25     0   0   0   0    0    0   0    0     0      0   ...       0      0   
26     0   0   0   0    0    0   0    0     0      0   ...       0      0   
27     0   0   0   0    0    0   0    0     0      0   ...       0      0   
28     0   0   0   0    0    0   0    0     0      0   ...       0      0   
29     0   0   0   0    0    0   0    0     0      0   ...       0      0   
...   ..  ..  ..  ..  ...  ...  ..  ...   ...    ...   ...     ...    ...   
1306   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1307   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1308   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1309   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1310   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1311   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1312   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1313   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1314   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1315   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1316   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1317   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1318   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1319   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1320   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1321   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1322   0   0   0   0    0    0   0    0     1      0   ...       0      0   
1323   0   0   0   0    0    0   0    0     0      0   ...       1      0   
1324   0   0   0   0    0    0   0    0     0      0   ...       0      0   
1325   0   0   0   0    0    0   0    0     0      0   ...       1      0   
13

In [23]:
#正解ラベル生成
Y_test = []
Y_valid = []
Y_train = []

with open("test.txt") as f1:
    for line in f1.readlines():
        Y_test.append(line.strip().split('\t')[4])
with open("valid.txt") as f2:
    for line in f2.readlines():
        Y_valid.append(line.strip().split('\t')[4])
with open("train.txt") as f3:
    for line in f3.readlines():
        Y_train.append(line.strip().split('\t')[4])

print(len(Y_test))
print(Y_test)
print(len(Y_valid))
print(Y_valid)
print(len(Y_train))
print(Y_train)

1336
['e', 'b', 'e', 'b', 'e', 't', 'b', 'e', 'e', 'e', 'e', 'b', 'm', 'b', 'b', 'e', 'e', 'e', 'm', 'b', 'b', 't', 'e', 'b', 'b', 't', 'b', 'e', 'b', 'b', 'b', 'e', 'b', 'e', 'b', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'b', 'b', 'b', 'm', 'b', 'e', 'e', 'm', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'e', 'b', 'b', 'b', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'b', 't', 'e', 'e', 't', 't', 'b', 'e', 't', 'b', 'e', 'e', 'e', 'b', 'e', 'e', 'e', 'b', 'm', 'e', 'e', 'e', 'b', 'e', 'e', 'b', 'b', 'e', 't', 't', 'b', 't', 'b', 'e', 'e', 'b', 'e', 'e', 'b', 'b', 'e', 'b', 'b', 'e', 'e', 'e', 't', 'b', 't', 'e', 'e', 'b', 'b', 'b', 'e', 'b', 'e', 't', 'e', 'b', 'b', 'e', 'b', 'e', 'm', 'b', 'b', 't', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'e', 'e', 'e', 'e', 'm', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'b', 'b', 'b', 'b', 'e', 'e', 'b', 'e', 'e', 'b', 't', 'b', 'e', 'e', 'e', 'm', 'b', 'b', 't', 'm', 'e', 'e', 'e', 'e', 'm', 'e', 't', 'e', 'm', 'e', 'e', 'e', 'm', 'm', 't', 'b', 'b', 'e', 'e', 'e', 't', 'b', 'b',

In [24]:
#52 CountVectorizer

lr = LogisticRegression() # ロジスティック回帰モデルのインスタンスを作成
lr.fit(X_train, Y_train) # ロジスティック回帰モデルの重みを学習

regression_coefficient = lr.coef_
segment = lr.intercept_
print(len(lr.coef_[1]))
print("coefficient = ", lr.coef_)
print("intercept = ", lr.intercept_)
print("決定係数:{}".format(lr.score(X_train, Y_train)))



13990
coefficient =  [[ 0.24027023  0.          0.         ... -0.0622969  -0.09402797
  -0.00378514]
 [-0.14168628  0.          0.         ...  0.14769359  0.11754139
   0.00951825]
 [-0.03797172  0.          0.         ... -0.02833721 -0.00511181
  -0.00498577]
 [-0.02336248  0.          0.         ... -0.02859111 -0.00618926
  -0.01650102]]
intercept =  [-1.00123167 -0.13665326 -3.59173955 -2.81144845]
決定係数:0.9894244267664951


In [25]:
#53 予測確率
probs = lr.predict_proba(X_test)
print(probs)


[[9.15308585e-04 9.97362631e-01 5.02324849e-04 1.21973542e-03]
 [4.71180361e-01 3.43657497e-03 2.82810737e-02 4.97101991e-01]
 [5.17862637e-02 2.12529287e-02 1.00407264e-03 9.25956735e-01]
 ...
 [9.53022907e-01 1.22275147e-02 3.26396369e-03 3.14856145e-02]
 [1.20362603e-01 7.56394926e-01 2.43397301e-02 9.89027407e-02]
 [5.30435237e-02 4.23964841e-02 8.13972077e-01 9.05879156e-02]]


In [26]:
#54 正答率
Y_pred = lr.predict(X_test)
print(len(Y_pred))
print(type(Y_pred))
print(Y_pred)
print(len(Y_pred == Y_test))
print(type(Y_pred == Y_test))
print(Y_pred == Y_test)
correct_answer = np.count_nonzero(Y_pred == Y_test)

print('正解率 : ' + str(correct_answer/ len(Y_pred)))

1336
<class 'numpy.ndarray'>
['e' 't' 't' ... 'b' 'e' 'm']
1336
<class 'numpy.ndarray'>
[ True False False ...  True  True  True]
正解率 : 0.9019461077844312


In [20]:

# TfidfVectorizer
t_vectorizer = TfidfVectorizer()


print(test_lines_list[0:3])
print(test_lines_list[0:3])

# ベクトル化 
t_vectorizer.fit(doc_lines_list)
print(type(t_vectorizer))

#特徴量の計算
X_test_t = t_vectorizer.transform(test_lines_list)
X_valid_t = t_vectorizer.transform(valid_lines_list)
X_train_t = t_vectorizer.transform(train_lines_list)

# print(type(X_test))
print(X_test_t)

#抽出した単語と出現回数の辞書
# tiidf_dict = t_vectorizer.vocabulary_
# print(type(tiidf_dict))
# print(len(tiidf_dict))
# print(tiidf_dict)

#抽出単語/各行　値：出現したかのバイナリ
pd.DataFrame(X_test_t.toarray(), columns=t_vectorizer.get_feature_names())
# test_feature = X_test.toarray()
# print(test_feature)

['Call the orthodontist! Miley Cyrus snarls as she shows off her joke snaggle  ...', 'Comcast-Time Warner Merger Faces State-Level Investigation', 'Spotify hits 40m users as Apple finalises Beats deal']
['Call the orthodontist! Miley Cyrus snarls as she shows off her joke snaggle  ...', 'Comcast-Time Warner Merger Faces State-Level Investigation', 'Spotify hits 40m users as Apple finalises Beats deal']
<class 'sklearn.feature_extraction.text.TfidfVectorizer'>
  (0, 12537)	0.12656446675613087
  (0, 11533)	0.4073745470416903
  (0, 11521)	0.4073745470416903
  (0, 11256)	0.23059228528760187
  (0, 11170)	0.21287429417544185
  (0, 8826)	0.4073745470416903
  (0, 8681)	0.21607133014810095
  (0, 8026)	0.22639265496084693
  (0, 6821)	0.32099253721371607
  (0, 5990)	0.19895189726461213
  (0, 3371)	0.2266598003556942
  (0, 2172)	0.2780361142707014
  (0, 1100)	0.1356238829532096
  (1, 13527)	0.35459371419761765
  (1, 12661)	0.2781702740610028
  (1, 11871)	0.3643759981839869
  (1, 7941)	0.3373775795

00   07   08   09  0ff  0ut   10       100      1000  10000   ...    \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
5     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
6     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
7     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
8     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
9     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
10    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
11    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
12    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
13    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
14    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
15    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
16    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
17    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
18    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
19    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.341947  0.000000    0.0   ...     
20    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
21    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
22    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
23    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
24    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
25    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
26    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
27    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
28    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
29    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
...   ...  ...  ...  ...  ...  ...  ...       ...       ...    ...   ...     
1306  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1307  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1308  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1309  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1310  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1311  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1312  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1313  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1314  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1315  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1316  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1317  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1318  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1319  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1320  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1321  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1322  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.338472    0.0   ...     
1323  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1324  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   ...     
1325  0.0  0.0  0.0  0.0  0.0

In [16]:
#52 TfidfVectorizer

lr = LogisticRegression() # ロジスティック回帰モデルのインスタンスを作成
lr.fit(X_train_t, Y_train) # ロジスティック回帰モデルの重みを学習

regression_coefficient = lr.coef_
segment = lr.intercept_
print(len(lr.coef_[1]))
print("coefficient = ", lr.coef_)
print("intercept = ", lr.intercept_)
print("決定係数:{}".format(lr.score(X_train_t, Y_train)))



13990
coefficient =  [[ 0.24217724  0.          0.         ... -0.07728692 -0.1106701
  -0.02438832]
 [-0.16239658  0.          0.         ...  0.13813242  0.13885563
   0.04807393]
 [-0.02830863  0.          0.         ... -0.0235983  -0.01336347
  -0.0150934 ]
 [-0.03590534  0.          0.         ... -0.0297783  -0.01616477
  -0.02693645]]
intercept =  [-0.77645875 -0.24965317 -2.83512791 -2.31734673]
決定係数:0.9229761347683668


In [17]:
#53 予測確率 TfidfVectorizer
probs = lr.predict_proba(X_test_t)
print(probs)


[[0.03439889 0.92464807 0.01854429 0.02240875]
 [0.52802721 0.0607213  0.06396183 0.34728966]
 [0.26845631 0.09622475 0.01923956 0.61607939]
 ...
 [0.82532822 0.08422163 0.02148732 0.06896283]
 [0.18415644 0.6582175  0.0515419  0.10608416]
 [0.24186086 0.23641225 0.38246765 0.13925924]]


In [18]:
#54 正答率 TfidfVectorizer
Y_pred_t = lr.predict(X_test_t)
print(len(Y_pred_t))
print(type(Y_pred_t))
print(Y_pred_t)
print(len(Y_pred_t == Y_test))
print(type(Y_pred_t == Y_test))
print(Y_pred_t == Y_test)
correct_answer_len = np.count_nonzero(Y_pred_t == Y_test)
print(correct_answer_len)
print(len(Y_pred_t))
print('正解率 : ' + str(correct_answer_len/ len(Y_pred_t)))

1336
<class 'numpy.ndarray'>
['e' 'b' 't' ... 'b' 'e' 'm']
1336
<class 'numpy.ndarray'>
[ True  True False ...  True  True  True]
1159
1336
正解率 : 0.8675149700598802
