In [81]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score


In [82]:
#51
#各ファイル読み込んでリスト化

#FORMAT: ID \t TITLE \t URL \t PUBLISHER \t CATEGORY \t STORY \t HOSTNAME \t TIMESTAMP

test_titles_list = []
valid_titles_list = []
train_titles_list = []


with open("test.txt") as f1:
    for line in f1.readlines():
        test_titles_list.append(line.strip().split('\t')[1])
with open("valid.txt") as f2:
    for line in f2.readlines():
        valid_titles_list.append(line.strip().split('\t')[1])
with open("train.txt") as f3:
    for line in f3.readlines():
        train_titles_list.append(line.strip().split('\t')[1])

print(test_titles_list[0:3])
print(valid_titles_list[0:3])
print(train_titles_list[0:3])

print(len(test_titles_list))
print(len(valid_titles_list))
print(len(train_titles_list))

all_titles_list = []
print(type(doc_lines_list))
all_titles_list.extend(test_titles_list)
all_titles_list.extend(valid_titles_list)
all_titles_list.extend(train_titles_list)

print(len(doc_lines_list))

['Call the orthodontist! Miley Cyrus snarls as she shows off her joke snaggle  ...', 'Comcast-Time Warner Merger Faces State-Level Investigation', 'Spotify hits 40m users as Apple finalises Beats deal']
['Aspirin to Prevent Heart Attack Should Be Limited, FDA Says (2)', 'PRECIOUS-Gold slips; platinum extends losses as Sth African strike ends', "Kerry Washington - Kerry Washington: Filming while pregnant is a 'challenge'"]
['Crumbs Surges After CNBC Says Lemonis Considering Rescue', 'Net Neutrality Must Be Defended', 'Gas prices fall over a penny in New Hampshire']
1336
1334
10685
<class 'list'>
13355


In [83]:

# CountVectorizer 
c_vectorizer = CountVectorizer(binary=True,  min_df=2, max_df=0.8)

# ベクトル化 
c_vectorizer.fit(all_titles_list)
print(type(c_vectorizer))

#特徴量の計算
X_test = c_vectorizer.transform(test_titles_list)
X_valid = c_vectorizer.transform(valid_titles_list)
X_train = c_vectorizer.transform(train_titles_list)

# print(type(X_test))
print(X_test)

#抽出した単語と出現回数の辞書
voc_count_dict = c_vectorizer.vocabulary_
# print(type(voc_count_dict))
# print(len(voc_count_dict))
# print(voc_count_dict)

#抽出単語/各行　値：出現したかのバイナリ
pd.DataFrame(X_test.toarray(), columns=c_vectorizer.get_feature_names())
# test_feature = X_test.toarray()
# print(test_feature)

<class 'sklearn.feature_extraction.text.CountVectorizer'>
  (0, 617)	1
  (0, 1257)	1
  (0, 1989)	1
  (0, 3617)	1
  (0, 4117)	1
  (0, 4885)	1
  (0, 5272)	1
  (0, 6788)	1
  (0, 6846)	1
  (0, 7614)	1
  (1, 1654)	1
  (1, 2826)	1
  (1, 3982)	1
  (1, 4428)	1
  (1, 4826)	1
  (1, 7203)	1
  (1, 7693)	1
  (1, 8224)	1
  (2, 112)	1
  (2, 559)	1
  (2, 617)	1
  (2, 841)	1
  (2, 2052)	1
  (2, 2982)	1
  (2, 3668)	1
  :	:
  (1333, 2264)	1
  (1333, 2442)	1
  (1333, 3447)	1
  (1333, 5307)	1
  (1333, 6781)	1
  (1333, 7915)	1
  (1333, 8015)	1
  (1333, 8045)	1
  (1333, 8120)	1
  (1334, 1892)	1
  (1334, 5142)	1
  (1334, 5340)	1
  (1334, 7532)	1
  (1334, 8378)	1
  (1335, 2960)	1
  (1335, 3011)	1
  (1335, 3100)	1
  (1335, 4027)	1
  (1335, 4216)	1
  (1335, 4447)	1
  (1335, 5638)	1
  (1335, 7710)	1
  (1335, 8041)	1
  (1335, 8056)	1
  (1335, 8138)	1


00  10  100  1000  100000  100k  100th  101  106  107  ...    zeppelin  \
0      0   0    0     0       0     0      0    0    0    0  ...           0   
1      0   0    0     0       0     0      0    0    0    0  ...           0   
2      0   0    0     0       0     0      0    0    0    0  ...           0   
3      0   0    0     0       0     0      0    0    0    0  ...           0   
4      0   0    0     0       0     0      0    0    0    0  ...           0   
5      0   0    0     0       0     0      0    0    0    0  ...           0   
6      0   0    0     0       0     0      0    0    0    0  ...           0   
7      0   0    0     0       0     0      0    0    0    0  ...           0   
8      0   0    0     0       0     0      0    0    0    0  ...           0   
9      0   0    0     0       0     0      0    0    0    0  ...           0   
10     0   0    0     0       0     0      0    0    0    0  ...           0   
11     0   0    0     0       0     0      0    0    0    0  ...           0   
12     0   0    0     0       0     0      0    0    0    0  ...           0   
13     0   0    0     0       0     0      0    0    0    0  ...           0   
14     0   0    0     0       0     0      0    0    0    0  ...           0   
15     0   0    0     0       0     0      0    0    0    0  ...           0   
16     0   0    0     0       0     0      0    0    0    0  ...           0   
17     0   0    0     0       0     0      0    0    0    0  ...           0   
18     0   0    0     0       0     0      0    0    0    0  ...           0   
19     0   0    1     0       0     0      0    0    0    0  ...           0   
20     0   0    0     0       0     0      0    0    0    0  ...           0   
21     0   0    0     0       0     0      0    0    0    0  ...           0   
22     0   0    0     0       0     0      0    0    0    0  ...           0   
23     0   0    0     0       0     0      0    0    0    0  ...           0   
24     0   0    0     0       0     0      0    0    0    0  ...           0   
25     0   0    0     0       0     0      0    0    0    0  ...           0   
26     0   0    0     0       0     0      0    0    0    0  ...           0   
27     0   0    0     0       0     0      0    0    0    0  ...           0   
28     0   0    0     0       0     0      0    0    0    0  ...           0   
29     0   0    0     0       0     0      0    0    0    0  ...           0   
...   ..  ..  ...   ...     ...   ...    ...  ...  ...  ...  ...         ...   
1306   0   0    0     0       0     0      0    0    0    0  ...           0   
1307   0   0    0     0       0     0      0    0    0    0  ...           0   
1308   0   0    0     0       0     0      0    0    0    0  ...           0   
1309   0   0    0     0       0     0      0    0    0    0  ...           0   
1310   0   0    0     0       0     0      0    0    0    0  ...           0   
1311   0   0    0     0       0     0      0    0    0    0  ...           0   
1312   0   0    0     0       0     0      0    0    0    0  ...           0   
1313   0   0    0     0       0     0      0    0    0    0  ...           0   
1314   0   0    0     0       0     0      0    0    0    0  ...           0   
1315   0   0    0     0       0     0      0    0    0    0  ...           0   
1316   0   0    0     0       0     0      0    0    0    0  ...           0   
1317   0   0    0     0       0     0      0    0    0    0  ...           0   
1318   0   0    0     0       0     0      0    0    0    0  ...           0   
1319   0   0    0     0       0     0      0    0    0    0  ...           0   
1320   0   0    0     0       0     0      0    0    0    0  ...           0   
1321   0   0    0     0       0     0      0    0    0    0  ...           0   
1322   0   0    0     1       0     0      0    0    0    0  ...           0   
1323   0   0    0     0       0     0      0    0    0    0  ...           0   
1324  

In [84]:
#正解ラベル生成
Y_test_true = []
Y_valid_true = []
Y_train_true = []

with open("test.txt") as f1:
    for line in f1.readlines():
        Y_test_true.append(line.strip().split('\t')[4])
with open("valid.txt") as f2:
    for line in f2.readlines():
        Y_valid_true.append(line.strip().split('\t')[4])
with open("train.txt") as f3:
    for line in f3.readlines():
        Y_train_true.append(line.strip().split('\t')[4])

print(len(Y_test_true))
print(Y_test_true)
print(len(Y_valid_true))
print(Y_valid_true)
print(len(Y_train_true))
print(Y_train_true)

1336
['e', 'b', 'e', 'b', 'e', 't', 'b', 'e', 'e', 'e', 'e', 'b', 'm', 'b', 'b', 'e', 'e', 'e', 'm', 'b', 'b', 't', 'e', 'b', 'b', 't', 'b', 'e', 'b', 'b', 'b', 'e', 'b', 'e', 'b', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'b', 'b', 'b', 'm', 'b', 'e', 'e', 'm', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'e', 'b', 'b', 'b', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'b', 't', 'e', 'e', 't', 't', 'b', 'e', 't', 'b', 'e', 'e', 'e', 'b', 'e', 'e', 'e', 'b', 'm', 'e', 'e', 'e', 'b', 'e', 'e', 'b', 'b', 'e', 't', 't', 'b', 't', 'b', 'e', 'e', 'b', 'e', 'e', 'b', 'b', 'e', 'b', 'b', 'e', 'e', 'e', 't', 'b', 't', 'e', 'e', 'b', 'b', 'b', 'e', 'b', 'e', 't', 'e', 'b', 'b', 'e', 'b', 'e', 'm', 'b', 'b', 't', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'e', 'e', 'e', 'e', 'm', 'b', 'b', 'e', 'e', 'e', 'e', 'b', 'b', 'b', 'b', 'b', 'e', 'e', 'b', 'e', 'e', 'b', 't', 'b', 'e', 'e', 'e', 'm', 'b', 'b', 't', 'm', 'e', 'e', 'e', 'e', 'm', 'e', 't', 'e', 'm', 'e', 'e', 'e', 'm', 'm', 't', 'b', 'b', 'e', 'e', 'e', 't', 'b', 'b',

In [85]:
#52 CountVectorizer

lr = LogisticRegression() # ロジスティック回帰モデルのインスタンスを作成
lr.fit(X_train, Y_train_true) # ロジスティック回帰モデルの重みを学習

regression_coefficient = lr.coef_
segment = lr.intercept_
print(len(lr.coef_[1]))
print("coefficient = ", lr.coef_)
print("intercept = ", lr.intercept_)
print("決定係数:{}".format(lr.score(X_train, Y_train_true)))



8526
coefficient =  [[ 0.22940173 -0.17505986  0.12650662 ...  0.20659915 -0.33835223
   0.1634932 ]
 [-0.1381549   0.22388323 -0.17530848 ... -0.26224994 -0.56029674
  -0.12662713]
 [-0.03811884  0.04127942  0.75729027 ... -0.06921481 -0.09851408
  -0.03076619]
 [-0.02292905  0.25133719 -0.84432407 ... -0.30856096  1.13121925
  -0.03906766]]
intercept =  [-0.99597292 -0.14129285 -3.53829274 -2.7324798 ]
決定係数:0.985212915301825


In [54]:
#53 予測確率
probs = lr.predict_proba(X_test)
print(probs)


[[9.20018937e-04 9.97356821e-01 4.93226121e-04 1.22993400e-03]
 [4.50368321e-01 3.53822090e-03 2.75185596e-02 5.18574898e-01]
 [4.85692821e-02 2.14501967e-02 1.00622440e-03 9.28974297e-01]
 ...
 [9.53733367e-01 1.15416098e-02 3.49791308e-03 3.12271098e-02]
 [1.20047972e-01 7.60027713e-01 2.42320907e-02 9.56922246e-02]
 [5.49210211e-02 3.67746005e-02 8.11940224e-01 9.63641540e-02]]


In [86]:
#54 正答率
Y_pred_c = lr.predict(X_test)
print(len(Y_pred_c))
print(type(Y_pred_c))
print(Y_pred_c)
print(len(Y_pred_c == Y_test_true))
print(type(Y_pred_c == Y_test_true))
print(Y_pred_c == Y_test_true)
correct_answer = np.count_nonzero(Y_pred_c == Y_test_true)

print('正解率 : ' + str(correct_answer/ len(Y_test_true)))

1336
<class 'numpy.ndarray'>
['e' 't' 't' ... 'b' 'e' 'm']
1336
<class 'numpy.ndarray'>
[ True False False ...  True  True  True]
正解率 : 0.9041916167664671


In [87]:

# TfidfVectorizer
t_vectorizer = TfidfVectorizer(binary=True,  min_df=2, max_df=0.8)

# ベクトル化 
t_vectorizer.fit(all_titles_list)
print(type(t_vectorizer))

#特徴量の計算
X_test_t = t_vectorizer.transform(test_titles_list)
X_valid_t = t_vectorizer.transform(valid_titles_list)
X_train_t = t_vectorizer.transform(train_titles_list)

# print(type(X_test))
print(X_test_t)

#抽出した単語と出現回数の辞書
# tiidf_dict = t_vectorizer.vocabulary_
# print(type(tiidf_dict))
# print(len(tiidf_dict))
# print(tiidf_dict)

#抽出単語/各行　値：出現したかのバイナリ
pd.DataFrame(X_test_t.toarray(), columns=t_vectorizer.get_feature_names())
# test_feature = X_test.toarray()
# print(test_feature)

<class 'sklearn.feature_extraction.text.TfidfVectorizer'>
  (0, 7614)	0.17860774092946594
  (0, 6846)	0.3254117700376313
  (0, 6788)	0.3004081458178187
  (0, 5272)	0.3049198021095261
  (0, 4885)	0.31948525286716933
  (0, 4117)	0.4529845808731474
  (0, 3617)	0.2807608630985857
  (0, 1989)	0.31986224837543714
  (0, 1257)	0.3923644885446593
  (0, 617)	0.19139238659322733
  (1, 8224)	0.35459371419761765
  (1, 7693)	0.2781702740610028
  (1, 7203)	0.3643759981839869
  (1, 4826)	0.3373775795666632
  (1, 4428)	0.38955327597818606
  (1, 3982)	0.37839348060475103
  (1, 2826)	0.37091609392459113
  (1, 1654)	0.3431894047195174
  (2, 8046)	0.3242156282122084
  (2, 7147)	0.40228798705317764
  (2, 3668)	0.2916859865927631
  (2, 2982)	0.4491481688013305
  (2, 2052)	0.24504750401266664
  (2, 841)	0.2993465306695552
  (2, 617)	0.15598044108043058
  :	:
  (1333, 8015)	0.1651013309044725
  (1333, 7915)	0.28808678023126943
  (1333, 6781)	0.24517678015594285
  (1333, 5307)	0.15588509926629615
  (1333, 3447)

00   10       100      1000  100000  100k  100th  101  106  107  ...    \
0     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
2     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
3     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
4     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
5     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
6     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
7     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
8     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
9     0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
10    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
11    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
12    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
13    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
14    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
15    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
16    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
17    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
18    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
19    0.0  0.0  0.341947  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
20    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
21    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
22    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
23    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
24    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
25    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
26    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
27    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
28    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
29    0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
...   ...  ...       ...       ...     ...   ...    ...  ...  ...  ...  ...     
1306  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1307  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1308  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1309  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1310  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1311  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1312  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1313  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1314  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1315  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1316  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1317  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1318  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1319  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1320  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1321  0.0  0.0  0.000000  0.000000     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1322  0.0  0.0  0.000000  0.412872     0.0   0.0    0.0  0.0  0.0  0.0  ...     
1323  0.0  0.0  0.000000  0.000000    

In [88]:
#52 TfidfVectorizer

lr = LogisticRegression() # ロジスティック回帰モデルのインスタンスを作成
lr.fit(X_train_t, Y_train_true) # ロジスティック回帰モデルの重みを学習

regression_coefficient = lr.coef_
segment = lr.intercept_
print(len(lr.coef_[1]))
print("coefficient = ", lr.coef_)
print("intercept = ", lr.intercept_)
print("決定係数:{}".format(lr.score(X_train_t, Y_train_true)))



8526
coefficient =  [[ 0.24379273  0.23905885  0.3363051  ...  0.91281985 -0.32946964
   0.30710685]
 [-0.16382891  0.07279692 -0.26493682 ... -0.71547961 -0.57969471
  -0.19191548]
 [-0.0266577  -0.22870747  0.67563908 ... -0.22661939 -0.09259741
  -0.04052569]
 [-0.03467328  0.08584092 -0.73421623 ... -0.51575643  1.15193312
  -0.07479624]]
intercept =  [-0.73840128 -0.26219892 -2.91219314 -2.36767282]
決定係数:0.9241927936359382


In [89]:
#53 予測確率 TfidfVectorizer
probs = lr.predict_proba(X_test_t)
print(probs)


[[0.01303018 0.96319798 0.01076551 0.01300633]
 [0.52490725 0.06107878 0.06072365 0.35329032]
 [0.26976307 0.09729483 0.01780807 0.61513403]
 ...
 [0.82345239 0.08586754 0.02206789 0.06861217]
 [0.20778543 0.62005503 0.0528952  0.11926433]
 [0.24390643 0.24323293 0.37730259 0.13555805]]


In [90]:
#54 正答率 TfidfVectorizer
Y_pred_t = lr.predict(X_test_t)
print(len(Y_pred_t))
print(type(Y_pred_t))
print(Y_pred_t)
print(len(Y_pred_t == Y_test_true))
print(type(Y_pred_t == Y_test_true))
print(Y_pred_t == Y_test_true)
correct_answer_len = np.count_nonzero(Y_pred_t == Y_test_true)
print(correct_answer_len)
print(len(Y_pred_t))
print('正解率 : ' + str(correct_answer_len/ len(Y_pred_t)))

1336
<class 'numpy.ndarray'>
['e' 'b' 't' ... 'b' 'e' 'm']
1336
<class 'numpy.ndarray'>
[ True  True False ...  True  True  True]
1172
1336
正解率 : 0.8772455089820359


In [91]:
#55 混合行列の作成
Y_pred_train_t = lr.predict(X_train_t)
confmat1 = confusion_matrix(Y_train_true, Y_pred_train_t)
print('混合行列_学習データ')
print(confmat1)


Y_pred_valid_t = lr.predict(X_valid_t)
confmat2 = confusion_matrix(Y_valid_true, Y_pred_valid_t)
print('混合行列_評価データ')
print(confmat2)

混合行列_学習データ
[[4339   98    4   43]
 [  24 4212    0    1]
 [ 107  165  460    5]
 [ 205  156    2  864]]
混合行列_評価データ
[[549  22   0   4]
 [  6 512   1   1]
 [ 21  31  34   1]
 [ 36  38   0  78]]


In [95]:
#56 適合率，再現率，F1スコアの計測

#適合率（precision）は、陽性と予測されたサンプルのうち正解したサンプルの割合。
print('適合率 C')
print(precision_score(Y_test_true, Y_pred, average='micro'))



適合率 C
0.9041916167664671


In [ ]:
from sklearn.metrics import recall_score

In [96]:
#再現率（recall）は実際に陽性のサンプルのうち正解したサンプルの割合。
#パラメータのaverageがわからない．binaryだとうまくいかないが，macroやmicroだとうまくいく

print('再現率 C')
print(recall_score(Y_test_true, Y_pred_c, average='macro'))
print(recall_score(Y_test_true, Y_pred_c, average='micro'))
print(recall_score(Y_test_true, Y_pred_c, average='weighted'))
#print(recall_score(Y_test, Y_pred, average='samples'))

再現率
0.8082752585633097
0.9041916167664671
0.9041916167664671


In [98]:
from sklearn.metrics import f1_score

In [100]:
#F1値（F1-measure）は適合率と再現率の調和平均。

print('F1値 C')
print(f1_score(Y_test_true, Y_pred_c, average='macro'))


F1値 C
0.8361781425900583
